import { getRepository, MigrationInterface, QueryRunner } from 'typeorm';
import { BbcodeEntity } from '../../persistance/entities/settings/bbcode.entity';

export class SeedBbcodesTable1600506005547 implements MigrationInterface {

    async up (queryRunner: QueryRunner): Promise<void> {
        await getRepository(BbcodeEntity).save([
            BbcodeEntity.newBuilder()
                .withName('bold')
                .withExample('[b]bold[/b]')
                .withPattern('\\[b\\](.+?)\\[\\/b\\]')
                .withReplacement('<strong>$1</strong>')
                .withEditorPattern('[b]{DATA}[/b]')
                .withEditorReplacement('<strong>{DATA}</strong>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('underline')
                .withExample('[u]underline[/u]')
                .withPattern('\\[u\\](.+?)\\[\\/u\\]')
                .withReplacement('<u>$1</u>')
                .withEditorPattern('[u]{DATA}[/u]')
                .withEditorReplacement('<u>{DATA}</u>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('strike')
                .withExample('[s]strike[/s]')
                .withPattern('\\[s\\](.+?)\\[\\/s\\]')
                .withReplacement('<s>$1</s>')
                .withEditorPattern('[s]{DATA}[/s]')
                .withEditorReplacement('<s>{DATA}</s>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('size')
                .withExample('[size=12]text[/size]')
                .withPattern('\\[size=(.+?)\\](.+?)\\[\\/size\\]')
                .withReplacement('<span style="font-size: $1px">$2</span>')
                .withEditorPattern('[size={SIZE}]{DATA}[/size]')
                .withEditorReplacement('<span style="font-size: {SIZE}px">{DATA}</span>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('font')
                .withExample('[font=Times New Roman]text[/font]')
                .withPattern('\\[font=(.+?)\\](.+?)\\[\\/font\\]')
                .withReplacement('<span style="font-family: $1">$2</span>')
                .withEditorPattern('[font={FONT}]{DATA}[/font]')
                .withEditorReplacement('<span style="font-family: {SIZE}">{DATA}</span>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('color')
                .withExample('[color=#000000]text[/color]')
                .withPattern('\\[color=(.+?)\\](.+?)\\[\\/color\\]')
                .withReplacement('<span style="color: $1">$2</span>')
                .withEditorPattern('[color={COLOR}]{DATA}[/font]')
                .withEditorReplacement('<span style="color: {COLOR}">{DATA}</span>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('table')
                .withExample('[table]table[/table]')
                .withPattern('\\[table\\](.+?)\\[\\/table\\]')
                .withReplacement('<table>$1</table>')
                .withEditorPattern('[table]{DATA}[/table]')
                .withEditorReplacement('<table>{DATA}</table>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('table row')
                .withExample('[tr]table row[/tr]')
                .withPattern('\\[tr\\](.+?)\\[\\/tr\\]')
                .withReplacement('<tr>$1</tr>')
                .withEditorPattern('[tr]{DATA}[/tr]')
                .withEditorReplacement('<tr>{DATA}</tr>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('table cell')
                .withExample('[td]table cell[/td]')
                .withPattern('\\[td\\](.+?)\\[\\/td\\]')
                .withReplacement('<td>$1</td>')
                .withEditorPattern('[td]{DATA}[/td]')
                .withEditorReplacement('<td>{DATA}</td>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('center')
                .withExample('[center]center[/center]')
                .withPattern('\\[center\\](.+?)\\[\\/center\\]')
                .withReplacement('<div style="text-align: center">$1</div>')
                .withEditorPattern('[center]{DATA}[/center]')
                .withEditorReplacement('<div style="text-align: center">{DATA}</div>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('left')
                .withExample('[left]left[/left]')
                .withPattern('\\[left\\](.+?)\\[\\/left\\]')
                .withReplacement('<div style="text-align: left">$1</div>')
                .withEditorPattern('[left]{DATA}[/left]')
                .withEditorReplacement('<div style="text-align: left">{DATA}</div>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('right')
                .withExample('[right]right[/right]')
                .withPattern('\\[right\\](.+?)\\[\\/right\\]')
                .withReplacement('<div style="text-align: right">$1</div>')
                .withEditorPattern('[right]{DATA}[/right]')
                .withEditorReplacement('<div style="text-align: right">{DATA}</div>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('url')
                .withExample('[url]link[/url]')
                .withPattern('\\[url\\](.+?)\\[\\/url\\]')
                .withReplacement('<a href="$1">$1</a>')
                .withEditorPattern('[url]{DATA}[/url]')
                .withEditorReplacement('<a href="{DATA}">{DATA}</a>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('url with text')
                .withExample('[url=link]text[/url]')
                .withPattern('\\[url=(.+?)\\](.+?)\\[\\/url\\]')
                .withReplacement('<a href="$1">$2</a>')
                .withEditorPattern('[url={LINK}]{DATA}[/url]')
                .withEditorReplacement('<a href="{LINK}">{DATA}</a>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('italic')
                .withExample('[i]bold[/i]')
                .withPattern('\\[i\\](.+?)\\[\\/i\\]')
                .withReplacement('<em>$1</em>')
                .withEditorPattern('[i]{DATA}[/i]')
                .withEditorReplacement('<i>{DATA}</i>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('order list')
                .withExample('[ol]list[/ol]')
                .withPattern('\\[ol\\](.+?)\\[\\/ol\\]')
                .withReplacement('<ol>$1</ol>')
                .withEditorPattern('[ol]{DATA}[/ol]')
                .withEditorReplacement('<ol>{DATA}</ol>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('list item')
                .withExample('[li]list item[/li]')
                .withPattern('\\[li\\](.+?)\\[\\/li\\]')
                .withReplacement('<li>$1</li>')
                .withEditorPattern('[li]{DATA}[/li]')
                .withEditorReplacement('<li>{DATA}</li>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('unordered list')
                .withExample('[ul]unordered list[/ul]')
                .withPattern('\\[ul\\](.+?)\\[\\/ul\\]')
                .withReplacement('<ul>$1</ul>')
                .withEditorPattern('[ul]{DATA}[/ul]')
                .withEditorReplacement('<ul>{DATA}</ul>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('image')
                .withExample('[img]image[/img]')
                .withPattern('\\[img\\](.+?)\\[\\/img\\]')
                .withReplacement('<img src="$1"/>')
                .withEditorPattern('[img]{DATA}[/img]')
                .withEditorReplacement('<img src="{DATA}" />')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('image with size')
                .withExample('[img width=10 height=10]image[/img]')
                .withPattern('\\[img width=(.+?) height=(.+?)\\](.+?)\\[\\/img\\]')
                .withReplacement('<img style="width: $1px; height: $2px;" src="$3"/>')
                .withEditorPattern('[img width={WIDTH} height={HEIGHT}]{DATA}[/img]')
                .withEditorReplacement('<img style="width: {WIDTH}px; height: {HEIGHT}px;" src="{DATA}" />')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('image right')
                .withExample('[imgr]image right[/imgr]')
                .withPattern('\\[imgr\\](.+?)\\[\\/imgr\\]')
                .withReplacement('<img src="$1" align="right" />')
                .withEditorPattern('[imgr]{DATA}[/imgr]')
                .withEditorReplacement('<img src="{DATA}" align="right" />')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('image left')
                .withExample('[imgl]image left[/imgl]')
                .withPattern('\\[imgl\\](.+?)\\[\\/imgl\\]')
                .withReplacement('<img src="$1" align="left" />')
                .withEditorPattern('[imgl]{DATA}[/imgl]')
                .withEditorReplacement('<img src="{DATA}" align="left" />')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('A title')
                .withExample('[atitle]title[/atitle]')
                .withPattern('\\[atitle\\](.+?)\\[\\/atitle\\]')
                .withReplacement('<div class="atitle">$1</div>')
                .withEditorPattern('[atitle]{DATA}[/atitle]')
                .withEditorReplacement('<div class="atitle">{DATA}</div>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('code')
                .withExample('[code]code[/code]')
                .withPattern('\\[code\\](.+?)\\[\\/code\\]')
                .withReplacement('<code>$1</code>')
                .withEditorPattern('[code]{DATA}[/code]')
                .withEditorReplacement('<code>{DATA}</code>')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('hr')
                .withExample('[hr]')
                .withPattern('\\[hr\\]')
                .withReplacement('<hr />')
                .withEditorPattern('[hr]')
                .withEditorReplacement('<hr />')
                .withIsSystem(true)
                .build(),
            BbcodeEntity.newBuilder()
                .withName('video')
                .withExample('[video]youtube ID[/video]')
                .withPattern('\\[video\\](.+?)\\[\\/video\\]')
                .withReplacement('<iframe src="https://www.youtube.com/embed/$1" width="640" height="480" frameborder="0"></iframe>')
                .withEditorPattern('[video]{DATA}[/video]')
                .withEditorReplacement('<iframe src="https://www.youtube.com/embed/{DATA}" width="640" height="480" frameborder="0"></iframe>')
                .withIsSystem(true)
                .build(),
        ]);
    }

    async down (queryRunner: QueryRunner): Promise<void> {
        // Empty
    }
}
