export enum LogTypes {
    CREATED_ARTICLE = 1,
    UPDATED_ARTICLE = 2,
    DELETED_ARTICLE = 3,
    APPROVED_ARTICLE = 4,
    UNAPPROVED_ARTICLE = 5,

    UPDATED_TIMETABLE_SLOT = 6,
    CREATED_TIMETABLE_SLOT = 7,
    DELETED_TIMETABLE_SLOT = 8,

    CREATED_EVENT = 9,
    DELETED_EVENT = 10,

    CREATED_GROUP = 11,
    UPDATED_GROUP = 12,
    DELETED_GROUP = 13,

    UPDATED_USER_DETAILS = 14,
    UPDATED_USER_GROUPS = 15,

    UPDATED_STAFF_LIST = 16
}
