export enum LogTypes {
    CREATED_ARTICLE = 1,
    UPDATED_ARTICLE = 2,
    DELETED_ARTICLE = 3,
    APPROVED_ARTICLE = 4,
    UNAPPROVED_ARTICLE = 5,

    UPDATED_TIMETABLE_SLOT = 6,
    CREATED_TIMETABLE_SLOT = 7,
    DELETED_TIMETABLE_SLOT = 8
}
